spring:
  application:
    name: foundation
  profiles:
    active: @spring.profiles@
  datasource:
    druid:
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 5
      minEvictableIdleTimeMillis: 300000
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: false
      timeBetweenEvictionRunsMillis: 60000
      validation-query: select 'x'
  jackson:
    default-property-inclusion: non_null

system:
  prefix:
    namespace1: /web
    namespace2: /mini
    namespace3: /mp
    namespace4: /open
  cron:
    every-day10: 0 0 10 * * ?
